---
configure_dotfiles: false
configure_terminal: false

configure_dock: false
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - Mail
 
configure_sudoers: true
sudoers_custom_config: |
   # Allow users in admin group to use sudo with no password.
   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc


homebrew_taps:
  - homebrew/core
  - hashicorp/tap
  - homebrew/cask
  - aws/tap
  
homebrew_installed_packages:
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - github/gh/gh
  - go
  - gpg
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - php
  - ssh-copy-id
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - zsh-history-substring-search
  - direnv
  - wget
  - git
  - git-gui
  - git-flow
  - golang
  - golangci-lint
  - keybase
  - aws-cli
  - node
  - rbenv
  - ruby-build
  - graphviz
  - kubectl
  - poetry
  - yarn
  - aws/tap/aws-sam-cli
  - docker-compose
  - eclipse-dsl
  - visual-studio-code
  - hashicorp-boundary-desktop
  - waypoint

homebrew_cask_apps:
  - obsidian
  - gpg-suite
  - chromedriver
  - docker
  - dropbox
  - firefox
  - google-chrome
  - handbrake
  - licecap
  - sequel-ace
  - slack
  - transmit
  - vagrant
  - virtualbox
  - vagrant-manager
  - amazon-workspaces

mas_uninstalled_apps:
  - { id: 408981434, name: "iMovie" }
  - { id: 409183694, name: "Keynote" }
  - { id: 409201541, name: "Pages" }
  - { id: 409203825, name: "Numbers" }
  - { id: 682658836, name: "GarageBand" }

gem_packages:
  - rake
  - semantic
  - os
  - uuid
  - random_username
  - inspec
  - bundler
  - test-kitchen
  - rubyzip

npm_packages:
  - grunt-cli

pip_packages:
  - pandas
  - pymongo
  - pipx

  